export type EquipmentItem = {
  category: string;           // e.g., "Bed", "Mattress"
  name: string;               // item name
  maxLoad: number;            // safe working load in kg
  location: string[];         // applicable locations, e.g., ["Hutt Wards"]
  procurement: string;        // how it is obtained
  compatibleBeds?: string[];  // for mattresses, which beds it's compatible with
  defaultForBeds?: string[];        // for mattresses, is it default for compatible bed
  notes?: string;             // optional description
};

export const equipmentList: EquipmentItem[] = [
  {
    category: 'Bed',
    name: 'Standard Bed',
    maxLoad: 180,
    location: ['Wellington Emergency Department', 'Wellington Wards', 'Hutt Emergency Department', 'Hutt Wards'],
    procurement: 'On Ward',
  },
  {
    category: 'Bed',
    name: 'Arjo Citadel w/ Auralis Mattress',
    maxLoad: 250,
    location: ['Hutt Emergency Department', 'Hutt Wards'],
    procurement: 'CEP',
    notes: 'Patients report uncomfortable to sit on the edge due to bed rails.',
  },
  {
    category: 'Bed',
    name: 'Arjo Citadel w/ Atmosair Mattress',
    maxLoad: 454,
    location: ['Hutt Emergency Department', 'Hutt Wards'],
    procurement: 'CEP',
    notes: 'Wide lying surface & power drive. Patients report uncomfortable to sit on the edge due to bed rails.',
  },
  {
    category: 'Bed',
    name: 'Essential Barry Bed',
    maxLoad: 500,
    location: ['Hutt Emergency Department', 'Hutt Wards'],
    procurement: 'Hire via Essential',
  },
  {
    category: 'Bed',
    name: 'Compella',
    maxLoad: 450,
    location: ['Hutt Emergency Department', 'Hutt Wards'],
    procurement: 'CEP',
    notes: 'Power width adjustment, built in air mattress plus turn function, power drive, low bed to floor height.',
  },

  {
    category: 'Mattress',
    name: 'Arjo Pentaflex',
    maxLoad: 180,
    location: ['Wellington Emergency Department', 'Wellington Wards', 'Hutt Emergency Department', 'Hutt Wards'],
    procurement: 'On Ward',
    compatibleBeds: ['Standard Bed'],
    defaultForBeds: ['Standard Bed'],
  },
  {
    category: 'Mattress',
    name: 'Arjo Auralis Alternating Air Mattress',
    maxLoad: 250,
    location: ['Hutt Emergency Department', 'Hutt Wards'],
    procurement: 'Hire via Arjo',
    compatibleBeds: ['Standard Bed', 'Arjo Citadel w/ Auralis Mattress'],
    defaultForBeds: ['Arjo Citadel w/ Auralis Mattress'],
  },
  {
    category: 'Mattress',
    name: 'Arjo Auralis Plus Mattress',
    maxLoad: 454,
    location: ['Hutt Emergency Department', 'Hutt Wards'],
    procurement: 'Hire via Arjo',
    compatibleBeds: ['Arjo Citadel w/ Auralis Mattress', 'Arjo Citadel w/ Atmosair Mattress'],
    notes: 'Alternative mattress for pressure care and turn assist.',
  },
  {
    category: 'Mattress',
    name: 'Atmosair Mattress',
    maxLoad: 454,
    location: ['Hutt Emergency Department', 'Hutt Wards'],
    procurement: 'CEP',
    compatibleBeds: ['Arjo Citadel w/ Atmosair Mattress'],
    defaultForBeds: ['Arjo Citadel w/ Atmosair Mattress'],
  },
  {
    category: 'Mattress',
    name: 'Hybird Mattress',
    maxLoad: 380,
    location: ['Hutt Emergency Department', 'Hutt Wards'],
    procurement: 'Hire via Essential',
    compatibleBeds: ['Essential Barry Bed'],
    defaultForBeds: ['Essential Barry Bed'],
  },
  {
    category: 'Mattress',
    name: 'Curocell',
    maxLoad: 220,
    location: ['Hutt Emergency Department', 'Hutt Wards'],
    procurement: 'CEP',
    compatibleBeds: ['Standard Bed', 'Arjo Citadel','Essential Barry Bed'],
  },
  {
    category: 'Mattress',
    name: 'PIPA Turn Mattress',
    maxLoad: 180,
    location: ['Hutt Emergency Department', 'Hutt Wards'],
    procurement: 'Hire via Essential',
    compatibleBeds: ['Standard Bed', 'Arjo Citadel','Essential Barry Bed'],
  },
  {
    category: 'Mattress',
    name: 'PIPA Air Mattress',
    maxLoad: 250,
    location: ['Hutt Emergency Department', 'Hutt Wards'],
    procurement: 'Hire via Essential',
    compatibleBeds: ['Standard Bed', 'Arjo Citadel','Essential Barry Bed'],
  },
  {
    category: 'Mattress',
    name: 'Compella Bed Mattress',
    maxLoad: 450,
    location: ['Hutt Emergency Department', 'Hutt Wards'],
    procurement: 'Included with bed',
    compatibleBeds: ['Compella'],
    defaultForBeds: ['Compella'],
  },
  {
    category: 'Mattress',
    name: 'Bariatric Alternating Air Mattress w/ Turning Option',
    maxLoad: 450,
    location: ['Hutt Emergency Department', 'Hutt Wards'],
    procurement: 'Hire via Essential',
    compatibleBeds: ['Essential Barry Bed'],
    notes: 'Alternative mattress for pressure care and turn assist.',
  },

  {
    category: 'Mat',
    name: 'Hovermat XL - Blue Handles (Arjo)',
    maxLoad: 544,
    location: ['Hutt Emergency Department', 'Hutt Wards'],
    procurement: 'Department based supplies via imprest',
    notes:'Requires pump from on ward supplies.',
  },
  {
    category: 'Mat',
    name: 'Hovermat XXL - Wide Orange Handles (Arjo)',
    maxLoad: 544,
    location: ['Hutt Emergency Department', 'Hutt Wards'],
    procurement: 'Department based supplies via imprest',
    notes: 'May require 2 pumps to ensure correct inflation. Request ',
  },
  
  {
    category: 'Commode',
    name: 'Shower Commode',
    maxLoad: 200,
    location: ['Hutt Wards', 'Hutt Emergency Department'],
    procurement: 'On Ward',
  },
  {
    category: 'Commode',
    name: 'Wide Seat Shower Commode',
    maxLoad: 300,
    location: ['Hutt Wards', 'Hutt Emergency Department'],
    procurement: 'On Ward',
  },
  {
    category: 'Commode',
    name: 'Tilt in Space Shower Commode',
    maxLoad: 200,
    location: ['Hutt Wards', 'Hutt Emergency Department'],
    procurement: 'CEP, Some Wards',
  },
  {
    category: 'Commode',
    name: 'Shower Trolley',
    maxLoad: 180,
    location: ['Hutt Wards', 'Hutt Emergency Department'],
    procurement: 'CEP',
  },
  {
    category: 'Commode',
    name: 'Be-Refreshed Tilting Shower Commode',
    maxLoad: 300,
    location: ['Hutt Wards', 'Hutt Emergency Department'],
    procurement: 'Hire via Essential',
  },
  {
    category: 'Commode',
    name: 'XL Shower Commode',
    maxLoad: 400,
    location: ['Hutt Wards', 'Hutt Emergency Department'],
    procurement: 'Hire via Essential',
    notes: 'Patients have reported insufficient seat depth for correct use and comfort.',
  },
  {
    category: 'Commode',
    name: 'XL Bariatric Tilt & Recline Shower Commode',
    maxLoad: 500,
    location: ['Hutt Wards', 'Hutt Emergency Department'],
    procurement: 'Hire via Essential',
  },
  
  {
    category: 'Hoist',
    name: 'Ceiling Hoist - 200kg',
    maxLoad: 200,
    location: ['Hutt Emergency Department', 'Hutt Wards'],
    procurement: 'OPRS & Medical Wards',
  },
  {
    category: 'Hoist',
    name: 'Ceiling Hoist - 450kg',
    maxLoad: 450,
    location: ['Hutt Emergency Department', 'Hutt Wards'],
    procurement: 'ICU / ED',
    notes: 'Any patient over 300kg needing to be hoisted in Hutt Hospital needs to be on ICU.',
  },
  {
    category: 'Hoist',
    name: 'Oxford Floor Hoist',
    maxLoad: 227,
    location: ['Hutt Emergency Department', 'Hutt Wards'],
    procurement: 'On Ward',
  },
  {
    category: 'Hoist',
    name: 'Molift Hoist with scales and 4 point spreader bar',
    maxLoad: 300,
    location: ['Hutt Emergency Department', 'Hutt Wards'],
    procurement: 'CEP',
    notes: 'Check CEP for correct or available sling size options. Consider injury risk when pushing with patient weight.',
  },

  {
    category: 'Slings',
    name: 'Standard Sling',
    maxLoad: 220,
    location: ['Hutt Emergency Department', 'Hutt Wards'],
    procurement: 'Ward based supplies',
    notes: 'Check sizing, refer to physio/OT.',
  },
  {
    category: 'Slings',
    name: 'Maxi Transfer Sheet - Regular',
    maxLoad: 272,
    location: ['Hutt Emergency Department', 'Hutt Wards'],
    procurement: 'ICU Supply, Ward Request Purchase via CEP',
  },
  {
    category: 'Slings',
    name: 'Maxi Transfer Sheet - Wide',
    maxLoad: 272,
    location: ['Hutt Emergency Department', 'Hutt Wards'],
    procurement: 'ICU Supply, Ward Request Purchase via CEP',
    notes: 'Wide width for expanded bed width.',
  },
  {
    category: 'Slings',
    name: 'Hoversling',
    maxLoad: 544,
    location: ['Hutt Emergency Department', 'Hutt Wards'],
    procurement: 'ICU Special order via imprest',
    notes: 'Critically requires 2 Hovertech pumps for inflation. May be indicated for patients with uneven weight distribution. Refer to M&H specialist.',
  },

  {
    category: 'Walking Aids',
    name: 'Standard Walker (Tubular Mobility)',
    maxLoad: 160,
    location: ['Hutt Wards'],
    procurement: 'CEP, On Ward',
  },
  {
    category: 'Walking Aids',
    name: '4 Wheeled Walker (Mobilis)',
    maxLoad: 120,
    location: ['Hutt Wards'],
    procurement: 'CEP',
  },
  {
    category: 'Walking Aids',
    name: 'Elbow Crutches (Coopers)',
    maxLoad: 180,
    location: ['Hutt Wards'],
    procurement: 'CEP',
  },
  {
    category: 'Walking Aids',
    name: 'Gutter Frame (Nomad)',
    maxLoad: 190,
    location: ['Hutt Wards'],
    procurement: 'CEP',
  },
  {
    category: 'Walking Aids',
    name: 'Walking Frame (Tubular Mobility)',
    maxLoad: 250,
    location: ['Hutt Wards'],
    procurement: 'CEP Store',
  },
  {
    category: 'Walking Aids',
    name: 'Gutter frame (Tubular Mobility)',
    maxLoad: 250,
    location: ['Hutt Wards'],
    procurement: 'CEP Store',
  },
  {
    category: 'Walking Aids',
    name: 'Bariatric Rollator',
    maxLoad: 325,
    location: ['Hutt Wards'],
    procurement: 'Hire via Essential',
  },

  {
    category: 'Wheelchairs',
    name: 'Stryker',
    maxLoad: 226,
    location: ['Hutt Wards'],
    procurement: 'General Use',
  },
  {
    category: 'Wheelchairs',
    name: 'Cloud Chair',
    maxLoad: 180,
    location: ['Hutt Wards'],
    procurement: 'CEP',
    notes:'Grey or brown, manual adjust, does not go flat.',
  },
  {
    category: 'Wheelchairs',
    name: 'Be Cosy Plus Power Hi-low Care Chair',
    maxLoad: 350,
    location: ['Hutt Wards'],
    procurement: 'Hire via Essential',
  },
  {
    category: 'Wheelchairs',
    name: 'Be Cosy Plus XL Power Hi-low Care Chair',
    maxLoad: 500,
    location: ['Hutt Wards'],
    procurement: 'Hire via Essential',
    notes: 'Increased risk of injury manually pushing this weight.',
  },
  {
    category: 'Wheelchairs',
    name: 'Eclipse self-propel wheelchair w/ suitable cushion',
    maxLoad: 454,
    location: ['Hutt Wards'],
    procurement: 'Hire via Permobile',
    notes: 'Increased risk of injury manually pushing this weight.',
  },
  
  {
    category: 'Bedside Chairs',
    name: 'High-back Bedside Chair',
    maxLoad: 200,
    location: ['Hutt Wards'],
    procurement: 'On Ward',
  },
  {
    category: 'Bedside Chairs',
    name: 'Be-Seated Bariatric Bedside Chair ',
    maxLoad: 400,
    location: ['Hutt Wards'],
    procurement: 'Hire via Essential',
    notes: 'Width can be adjusted.',
  },
  {
    category: 'Bedside Chairs',
    name: 'Be-Seated Plus XL Bariatric Bedside Chair ',
    maxLoad: 450,
    location: ['Hutt Wards'],
    procurement: 'Hire via Essential',
  },
];