import { LocationCode, sites } from './locations';

export type ProcurementBySite = {
  Wellington: string;
  Hutt: string;
};

export type EquipmentItem = {
  category: string;            // e.g., "Bed", "Mattress"
  name: string;                // item name
  maxLoad: number;             // safe working load in kg
  minLoad?: number;            // optional min load for equipment filtering
  seatWidth?: number;           // seat width in cm of wheelchairs, commodes, bedside chairs
  width?: number;               // width of equipment in cm, used for hovermats (surface width)
  location: LocationCode[];    // applicable location codes
  procurement: ProcurementBySite; // site-specific procurement
  notes?: string;              // optional description
};

export const equipmentList: EquipmentItem[] = [
  {
    category: 'Bed + Mattress',
    name: 'Standard Bed w/ Arjo Pentaflex Mattress',
    maxLoad: 180,
    location: [...sites.Wellington, ...sites.Hutt],
    procurement: { Wellington: 'On Ward', Hutt: 'On Ward' },
  },
  {
    category: 'Bed + Mattress',
    name: 'Arjo Citadel w/ Auralis Mattress',
    maxLoad: 250,
    location: [...sites.Wellington, ...sites.Hutt],
    procurement: { Wellington: 'ICU / Hire via Arjo', Hutt: 'CEP' },
    notes: 'Patients report uncomfortable to sit on the edge due to bed rails.',
  },
  {
    category: 'Bed + Mattress',
    name: 'Arjo Citadel w/ Atmosair Mattress',
    maxLoad: 454,
    minLoad: 251,
    location: [...sites.Wellington, ...sites.Hutt],
    procurement: { Wellington: 'ICU / Bed store / Hire via Arjo', Hutt: 'CEP' },
    notes: 'Wide lying surface & power drive. Patients report uncomfortable to sit on the edge due to bed rails.',
  },
  {
    category: 'Bed + Mattress',
    name: 'Essential Barry Bed w/ Standard Bariatric Hybrid Mattress',
    maxLoad: 380,
    location: [...sites.Wellington, ...sites.Hutt],
    procurement: { Wellington: 'Hire via Essential', Hutt: 'Hire via Essential' },
  },
  {
    category: 'Bed + Mattress',
    name: 'Essential Barry Bed w/ Q5 ProCare Bariatric Air Mattress',
    maxLoad: 450,
    minLoad: 381,
    location: [...sites.Wellington, ...sites.Hutt],
    procurement: { Wellington: 'Hire via Essential', Hutt: 'Hire via Essential' },
    notes: 'Alternating air mattress for pressure care.'
  },
  {
    category: 'Bed + Mattress',
    name: 'Compella w/ Compella Mattress',
    maxLoad: 450,
    minLoad: 251,
    location: [...sites.Hutt],
    procurement: { Wellington: '', Hutt: 'CEP' },
    notes: 'Power width adjustment, built in air mattress plus turn function, power drive, low bed to floor height.',
  },

  {
    category: 'Hovermat',
    name: 'Hovermat XL - Blue Handles (Arjo)',
    maxLoad: 544,
    width: 99,
    location: [...sites.Wellington, ...sites.Hutt],
    procurement: { Wellington: 'Department based supplies via imprest', Hutt: 'Department based supplies via imprest' },
    notes:'Requires pump from on ward supplies.',
  },
  {
    category: 'Hovermat',
    name: 'Hovermat XXL - Wide Orange Handles (Arjo)',
    maxLoad: 544,
    width: 127,
    location: [...sites.Wellington, ...sites.Hutt],
    procurement: { Wellington: 'Department based supplies via imprest', Hutt: 'Department based supplies via imprest' },
    notes: 'May require 2 pumps to ensure correct inflation. Request ',
  },
  
  {
    category: 'Commode Options',
    name: 'Static Commode',
    maxLoad: 120,
    seatWidth: 46,
    location: [...sites.Wellington],
    procurement: { Wellington: 'On Ward', Hutt: 'NA' },
  },
  {
    category: 'Commode Options',
    name: 'Wide Static Commode',
    maxLoad: 225,
    seatWidth: 65,
    location: [...sites.Wellington],
    procurement: { Wellington: 'CEP', Hutt: 'NA' },
  },
  {
    category: 'Commode Options',
    name: 'Shower Commode',
    maxLoad: 200,
    seatWidth: 49,
    location: [...sites.Wellington, ...sites.Hutt],
    procurement: { Wellington: 'On Ward', Hutt: 'On Ward' },
  },
  {
    category: 'Commode Options',
    name: 'Wide Seat Shower Commode',
    maxLoad: 300,
    seatWidth: 53,
    location: [...sites.Wellington, ...sites.Hutt],
    procurement: { Wellington: 'On Ward', Hutt: 'On Ward' },
  },
  {
    category: 'Commode Options',
    name: 'Tilt in Space Shower Commode',
    maxLoad: 200,
    seatWidth: 49,
    location: [...sites.Wellington, ...sites.Hutt],
    procurement: { Wellington: 'CEP, Some Wards', Hutt: 'CEP, Some Wards' },
  },
  {
    category: 'Commode Options',
    name: 'Shower Trolley',
    maxLoad: 180,
    seatWidth: 83,
    location: [...sites.Wellington, ...sites.Hutt],
    procurement: { Wellington: 'ICU', Hutt: 'CEP' },
  },
  {
    category: 'Commode Options',
    name: 'Be-Refreshed Powered Tilting Shower Commode',
    maxLoad: 300,
    seatWidth: 70,
    location: [...sites.Wards],
    procurement: { Wellington: 'Hire via Essential', Hutt: 'Hire via Essential' },
  },
  {
    category: 'Commode Options',
    name: 'XL Shower Commode Non-Tilt',
    maxLoad: 400,
    minLoad: 200,
    seatWidth: 91,
    location: [...sites.Wellington, ...sites.Hutt],
    procurement: { Wellington: 'Hire via Essential', Hutt: 'Hire via Essential' },
    notes: 'Patients have reported insufficient seat depth for correct use and comfort.',
  },
  {
    category: 'Commode Options',
    name: 'XL Bariatric Tilt & Recline Shower Commode',
    maxLoad: 500,
    minLoad: 200,
    seatWidth: 89,
    location: [...sites.Wards],
    procurement: { Wellington: 'Hire via Essential', Hutt: 'Hire via Essential' },
  },
  
  {
    category: 'Hoist',
    name: 'Ceiling Hoist - 200kg',
    maxLoad: 200,
    location: [...sites.Hutt],
    procurement: { Wellington: 'NA', Hutt: 'OPRS & Medical Wards' },
  },
  {
    category: 'Hoist',
    name: 'Ceiling Hoist - Guldmann - 255kg',
    maxLoad: 255,
    location: [...sites.Wellington],
    procurement: { Wellington: 'On Ward', Hutt: 'NA' },
  },
  {
    category: 'Hoist',
    name: 'Ceiling Hoist - 400kg',
    maxLoad: 400,
    location: [...sites.Wellington],
    procurement: { Wellington: 'On Ward', Hutt: 'NA' },
    notes: 'Check specific room for this hoist: 7S - E16, 7N - B16, 7E - B12, 6S - E17, 6N - B15, 6E - B15 5S - B14, 5N - F27. Bed spaces with difficult access for bariatric beds on 6 East and 6 South',
  },
    {
    category: 'Hoist',
    name: 'Ceiling Hoist - 500kg',
    maxLoad: 500,
    location: [...sites.Wellington],
    procurement: { Wellington: 'ICU - Room 16', Hutt: 'NA' },
    notes: 'Any patient over 400kg needing to be hoisted in Wellington needs to be on ICU.',
  },
  {
    category: 'Hoist',
    name: 'Ceiling Hoist - 450kg',
    maxLoad: 450,
    location: [...sites.HuttED],
    procurement: { Wellington: 'NA', Hutt: 'ICU / ED' },
    notes: 'Any patient over 300kg needing to be hoisted in Hutt Hospital needs to be on ICU.',
  },
  {
    category: 'Hoist',
    name: 'Oxford Floor Hoist',
    maxLoad: 227,
    location: [...sites.Hutt],
    procurement: { Wellington: 'NA', Hutt: 'On Ward' },
  },
  {
    category: 'Hoist',
    name: 'Floor Hoist - Arjo',
    maxLoad: 227,
    location: [...sites.Wellington],
    procurement: { Wellington: 'On Ward', Hutt: 'NA' },
  },
  {
    category: 'Hoist',
    name: 'Molift Hoist with scales and 4 point spreader bar',
    maxLoad: 300,
    location: [...sites.Hutt],
    procurement: { Wellington: 'NA', Hutt: 'CEP' },
    notes: 'Check CEP for correct or available sling size options. Consider injury risk when pushing with patient weight.',
  },
  {
    category: 'Hoist',
    name: 'Arjo Tenor Hoist with 4 point spreader bar',
    maxLoad: 320,
    location: [...sites.Wellington],
    procurement: { Wellington: 'CEP', Hutt: 'NA' },
    notes: 'Check CEP for correct or available sling size options. Consider injury risk when pushing with patient weight.',
  },

  {
    category: 'Slings',
    name: 'Standard Sling',
    maxLoad: 220,
    location: [...sites.Wellington, ...sites.Hutt],
    procurement: { Wellington: 'Ward based supplies', Hutt: 'Ward based supplies' },
    notes: 'Check sizing, refer to physio/OT.',
  },
  {
    category: 'Slings',
    name: 'Maxi Transfer Sheet - Regular',
    maxLoad: 272,
    location: [...sites.Wellington, ...sites.Hutt],
    procurement: { Wellington: 'ICU Supply, Ward Request Purchase via CEP', Hutt: 'ICU Supply, Ward Request Purchase via CEP' },
  },
  {
    category: 'Slings',
    name: 'Maxi Transfer Sheet - Wide',
    maxLoad: 272,
    location: [...sites.Wellington, ...sites.Hutt],
    procurement: { Wellington: 'ICU Supply, Ward Request Purchase via CEP', Hutt: 'ICU Supply, Ward Request Purchase via CEP' },
    notes: 'Wide width for expanded bed width.',
  },
  {
    category: 'Slings',
    name: 'Hoversling',
    maxLoad: 544,
    minLoad: 200,
    location: [...sites.Wellington, ...sites.Hutt],
    procurement: { Wellington: 'Special order via imprest', Hutt: 'ICU Special order via imprest' },
    notes: 'Critically requires 2 Hovertech pumps for inflation. May be indicated for patients with uneven weight distribution. Refer to M&H specialist.',
  },

  {
    category: 'Walking Aids',
    name: 'Standard Walker (Tubular Mobility)',
    maxLoad: 160,
    location: [...sites.Wellington, ...sites.Hutt],
    procurement: { Wellington: 'CEP, On Ward', Hutt: 'CEP, On Ward' },
  },
  {
    category: 'Walking Aids',
    name: '4 Wheeled Walker (Mobilis)',
    maxLoad: 120,
    location: [...sites.Wellington, ...sites.Hutt],
    procurement: { Wellington: 'CEP', Hutt: 'CEP' },
  },
  {
    category: 'Walking Aids',
    name: 'Elbow Crutches (Coopers)',
    maxLoad: 180,
    location: [...sites.Wellington, ...sites.Hutt],
    procurement: { Wellington: 'CEP', Hutt: 'CEP' },
  },
  {
    category: 'Walking Aids',
    name: 'Gutter Frame (Nomad)',
    maxLoad: 190,
    location: [...sites.Wellington, ...sites.Hutt],
    procurement: { Wellington: 'CEP', Hutt: 'CEP' },
  },
  {
    category: 'Walking Aids',
    name: 'Walking Frame (Tubular Mobility)',
    maxLoad: 250,
    location: [...sites.Wellington, ...sites.Hutt],
    procurement: { Wellington: 'CEP', Hutt: 'CEP' },
  },
  {
    category: 'Walking Aids',
    name: 'Gutter frame (Tubular Mobility)',
    maxLoad: 250,
    location: [...sites.Wellington, ...sites.Hutt],
    procurement: { Wellington: 'CEP', Hutt: 'CEP' },
  },
  {
    category: 'Walking Aids',
    name: '4 Wheeled Stroller with Seat',
    maxLoad: 350,
    location: [...sites.Wellington],
    procurement: { Wellington: 'CEP', Hutt: 'NA' },
  },
  {
    category: 'Walking Aids',
    name: 'Bariatric Rollator',
    maxLoad: 325,
    minLoad: 200,
    location: [...sites.Wellington, ...sites.Hutt],
    procurement: { Wellington: 'Hire via Essential', Hutt: 'Hire via Essential' },
  },

  {
    category: 'Wheelchairs',
    name: 'Stryker',
    maxLoad: 226,
    seatWidth: 54,
    location: [...sites.Wellington, ...sites.Hutt],
    procurement: { Wellington: 'General Use', Hutt: 'General Use' },
  },
  {
    category: 'Wheelchairs',
    name: 'Cloud Chair',
    maxLoad: 180,
    seatWidth: 60,
    location: [...sites.Wellington, ...sites.Hutt],
    procurement: { Wellington: 'CEP', Hutt: 'CEP' },
    notes:'Comes in grey, brown or blue. Manual adjust, does not go flat.',
  },
  {
    category: 'Wheelchairs',
    name: 'Be Cosy Powered Hi-low Care Chair',
    maxLoad: 160,
    seatWidth: 52,
    location: [...sites.Wellington, ...sites.Hutt],
    procurement: { Wellington: 'Hire via Essential', Hutt: 'Hire via Essential' },
  },
  {
    category: 'Wheelchairs',
    name: 'Be Cosy Plus Powered Hi-low Care Chair',
    maxLoad: 350,
    minLoad: 160,
    seatWidth: 72,
    location: [...sites.Wellington, ...sites.Hutt],
    procurement: { Wellington: 'Hire via Essential', Hutt: 'Hire via Essential' },
  },
  {
    category: 'Wheelchairs',
    name: 'Be Cosy Plus XL Powered Hi-low Care Chair',
    maxLoad: 500,
    minLoad: 200,
    seatWidth: 95,
    location: [...sites.Wellington, ...sites.Hutt],
    procurement: { Wellington: 'Hire via Essential', Hutt: 'Hire via Essential' },
    notes: 'Increased risk of injury manually pushing this weight.',
  },
  {
    category: 'Wheelchairs',
    name: 'Eclipse self-propel wheelchair w/ suitable cushion',
    maxLoad: 454,
    minLoad: 200,
    location: [...sites.Wellington, ...sites.Hutt],
    procurement: { Wellington: 'Hire via Permobile', Hutt: 'Hire via Permobile' },
    notes: 'Increased risk of injury manually pushing this weight.',
  },
  
  {
    category: 'Bedside Chairs',
    name: 'High-back Bedside Chair',
    maxLoad: 200,
    seatWidth: 52,
    location: [...sites.Wellington, ...sites.Hutt],
    procurement: { Wellington: 'On Ward', Hutt: 'On Ward' },
  },
  {
    category: 'Bedside Chairs',
    name: 'High-back Maxi Chair',
    maxLoad: 250,
    seatWidth: 60,
    location: [...sites.Wellington],
    procurement: { Wellington: 'CEP', Hutt: 'NA' },
  },
  {
    category: 'Bedside Chairs',
    name: 'Utility Chair (Low back)',
    maxLoad: 250,
    seatWidth: 56,
    location: [...sites.Wellington],
    procurement: { Wellington: 'CEP', Hutt: 'NA' },
  },
  {
    category: 'Bedside Chairs',
    name: 'Be-Seated Bariatric Bedside Chair ',
    maxLoad: 400,
    seatWidth: 75,
    location: [...sites.Wellington, ...sites.Hutt],
    procurement: { Wellington: 'Hire via Essential', Hutt: 'Hire via Essential' },
    notes: 'Width can be adjusted.',
  },
  {
    category: 'Bedside Chairs',
    name: 'Be-Seated Plus XL Bariatric Bedside Chair ',
    maxLoad: 450,
    seatWidth: 100,
    location: [...sites.Wellington, ...sites.Hutt],
    procurement: { Wellington: 'Hire via Essential', Hutt: 'Hire via Essential' },
  },

  {
    category: 'Accessories',
    name: 'Air Supply for Hovermat',
    maxLoad: -1,
    location: [...sites.Wellington, ...sites.Hutt],
    procurement: { Wellington: 'On Ward', Hutt: 'On Ward' },
  },
  {
    category: 'Accessories',
    name: '2x Air Supply for Hovermat',
    maxLoad: -1,
    location: [...sites.Wellington, ...sites.Hutt],
    procurement: { Wellington: 'On Ward & CEP', Hutt: 'On Ward & CEP' },
    notes: '1 Air Supply already On Ward, order additional pump for proper inflation.',
  },
  {
    category: 'Accessories',
    name: '2x Hovertech Pumps',
    maxLoad: -1,
    location: [...sites.Wellington, ...sites.Hutt],
    procurement: { Wellington: 'CEP', Hutt: 'CEP' },
    notes: 'Hovertech pumps required for Hoversling.',
  },
];